In [94]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse

In [2]:
parkinson_data = pd.read_csv('parkinson_data.csv')
parkinson_data

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0    phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1    phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2    phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3    phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4    phon_R01_S01_5      116.014       141.781       110.655         0.01284   
..              ...          ...           ...           ...             ...   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0             0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1             0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2             0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3             0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4             0.00011   0.00655   0.00908     0.01966       0.06425  ...   
..                ...       ...       ...         ...           ...  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0        0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1        0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2        0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3        0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4        0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   
..           ...      ...     ...     ...       ...       ...       ...   
190      0.07008  0.02764  19.517       0  0.448439  0.657899 -6.538586   
191      0.04812  0.01810  19.147       0  0.431674  0.683244 -6.195325   
192      0.03804  0.10715  17.883       0  0.407567  0.655683 -6.787197   
193      0.03794  0.07223  19.020       0  0.451221  0.643956 -6.744577   
194      0.03078  0.04398  21.209       0  0.462803  0.664357 -5.724056   

      spread2        D2       PPE  
0    0.266482  2.301442  0.284654  
1    0.335590  2.486855  0.368674  
2    0.311173  2.342259  0.332634  
3    0.334147  2.405554  0.368975  
4    0.234513  2.332180  0.410335  
..        ...       ...       ...  
190  0.121952  2.657476  0.133050  
191  0.129303  2.784312  0.168895  
192  0.158453  2.679772  0.131728  
193  0.207454  2.138608  0.123306  
194  0.190667  2.555477  0.148569  

[195 rows x 24 columns]

In [3]:
y = parkinson_data['RPDE'] # target

In [77]:
X = parkinson_data.drop(['RPDE', 'name'], axis =1)
X

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        122.400       148.650       113.819         0.00968   
2        116.682       131.111       111.555         0.01050   
3        116.676       137.871       111.366         0.00997   
4        116.014       141.781       110.655         0.01284   
..           ...           ...           ...             ...   
190      174.188       230.978        94.261         0.00459   
191      209.516       253.017        89.488         0.00564   
192      174.688       240.005        74.287         0.01360   
193      198.764       396.961        74.904         0.00740   
194      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00008   0.00465   0.00696     0.01394       0.06134   
2             0.00009   0.00544   0.00781     0.01633       0.05233   
3             0.00009   0.00502   0.00698     0.01505       0.05492   
4             0.00011   0.00655   0.00908     0.01966       0.06425   
..                ...       ...       ...         ...           ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087   
191           0.00003   0.00331   0.00292     0.00994       0.02751   
192           0.00008   0.00624   0.00564     0.01873       0.02308   
193           0.00004   0.00370   0.00390     0.01109       0.02296   
194           0.00003   0.00295   0.00317     0.00885       0.01884   

     MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA      NHR     HNR  status  \
0               0.426  ...   0.02971      0.06545  0.02211  21.033       1   
1               0.626  ...   0.04368      0.09403  0.01929  19.085       1   
2               0.482  ...   0.03590      0.08270  0.01309  20.651       1   
3               0.517  ...   0.03772      0.08771  0.01353  20.644       1   
4               0.584  ...   0.04465      0.10470  0.01767  19.649       1   
..                ...  ...       ...          ...      ...     ...     ...   
190             0.405  ...   0.02745      0.07008  0.02764  19.517       0   
191             0.263  ...   0.01879      0.04812  0.01810  19.147       0   
192             0.256  ...   0.01667      0.03804  0.10715  17.883       0   
193             0.241  ...   0.01588      0.03794  0.07223  19.020       0   
194             0.190  ...   0.01373      0.03078  0.04398  21.209       0   

          DFA   spread1   spread2        D2       PPE  
0    0.815285 -4.813031  0.266482  2.301442  0.284654  
1    0.819521 -4.075192  0.335590  2.486855  0.368674  
2    0.825288 -4.443179  0.311173  2.342259  0.332634  
3    0.819235 -4.117501  0.334147  2.405554  0.368975  
4    0.823484 -3.747787  0.234513  2.332180  0.410335  
..        ...       ...       ...       ...       ...  
190  0.657899 -6.538586  0.121952  2.657476  0.133050  
191  0.683244 -6.195325  0.129303  2.784312  0.168895  
192  0.655683 -6.787197  0.158453  2.679772  0.131728  
193  0.643956 -6.744577  0.207454  2.138608  0.123306  
194  0.664357 -5.724056  0.190667  2.555477  0.148569  

[195 rows x 22 columns]

In [78]:
parkinson_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 494)

In [80]:
y_train

22     0.619060
74     0.437031
5      0.415564
160    0.653139
71     0.543299
         ...   
115    0.407701
122    0.538016
79     0.594387
159    0.654945
12     0.460600
Name: RPDE, Length: 165, dtype: float64

In [81]:
model = LinearRegression()

In [83]:
model.fit(X_train, y_train)

LinearRegression()

In [88]:
model.coef_

array([-1.42249538e-04,  5.12290780e-05, -1.16946680e-04, -3.02354942e+01,
        2.08097251e+03,  2.48150040e+03, -4.94580151e+00, -8.19961125e+02,
        1.62892773e+00, -4.30157275e-01,  1.31502906e+03, -6.47998731e+00,
        6.51926248e+00, -4.37569379e+02, -1.39530461e-01, -1.92802376e-02,
       -3.44909028e-02, -4.46317816e-01,  3.10989086e-02,  3.53511635e-01,
       -9.51718586e-02, -4.62291560e-02])

In [87]:
model.intercept_

1.66787033241306

In [ ]:
y = -1.42x1 + 5.12x2 + -1.16x3 + ........ + 1.67

In [89]:
X_test

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
174      117.004       144.466        99.923         0.00353   
11        91.904       115.871        86.292         0.00540   
49       122.964       130.049       114.676         0.00428   
55       109.860       126.358       104.437         0.00874   
10        88.333       112.240        84.072         0.00505   
150      186.695       211.961       149.442         0.01872   
52       128.001       138.052       122.080         0.00436   
137      113.166       130.270       100.673         0.00502   
87       176.281       227.381       125.610         0.00520   
99       126.512       141.756        99.770         0.01936   
107      151.884       157.765       133.751         0.00258   
98       125.791       140.557        96.206         0.01378   
156      122.336       142.369        94.794         0.00727   
7        107.332       113.840       104.315         0.00290   
69       148.090       162.824        67.343         0.00762   
65       228.969       239.541       113.201         0.00238   
121      176.824       215.293        83.961         0.00460   
40       186.163       197.724       177.584         0.00298   
42       237.226       247.326       225.227         0.00298   
78        95.385       102.145        90.264         0.00608   
26       171.041       208.313        75.501         0.00455   
146      169.774       191.759       151.451         0.01568   
161      115.322       135.738       107.802         0.00619   
31       199.228       209.512       192.091         0.00241   
191      209.516       253.017        89.488         0.00564   
102      139.224       586.567        66.157         0.03011   
118      178.285       442.824        82.063         0.00462   
181      148.462       161.078       141.998         0.00397   
37       176.170       185.604       163.564         0.00369   
165      236.200       244.663       102.137         0.00277   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
174           0.00003   0.00176   0.00218     0.00528       0.01657   
11            0.00006   0.00281   0.00336     0.00844       0.02752   
49            0.00003   0.00124   0.00155     0.00373       0.01681   
55            0.00008   0.00398   0.00539     0.01193       0.03209   
10            0.00006   0.00254   0.00330     0.00763       0.02143   
150           0.00010   0.01075   0.01154     0.03225       0.05830   
52            0.00003   0.00137   0.00166     0.00411       0.02297   
137           0.00004   0.00257   0.00312     0.00772       0.05279   
87            0.00003   0.00287   0.00312     0.00862       0.06511   
99            0.00015   0.01159   0.00990     0.03476       0.06734   
107           0.00002   0.00115   0.00122     0.00346       0.01450   
98            0.00011   0.00826   0.00655     0.02478       0.04689   
156           0.00006   0.00415   0.00339     0.01246       0.02293   
7             0.00003   0.00144   0.00182     0.00431       0.01567   
69            0.00005   0.00467   0.00354     0.01400       0.05428   
65            0.00001   0.00136   0.00140     0.00408       0.01745   
121           0.00003   0.00209   0.00221     0.00628       0.01169   
40            0.00002   0.00165   0.00175     0.00496       0.01495   
42            0.00001   0.00169   0.00182     0.00507       0.01752   
78            0.00006   0.00331   0.00332     0.00994       0.03202   
26            0.00003   0.00250   0.00234     0.00750       0.01966   
146           0.00009   0.00863   0.00946     0.02589       0.08143   
161           0.00005   0.00352   0.00329     0.01057       0.03273   
31            0.00001   0.00134   0.00138     0.00402       0.01015   
191           0.00003   0.00331   0.00292     0.00994       0.02751   
102           0.00022   0.01854   0.01628     0.05563       0.09419   
118           0.00003   0.00157   0.00194     0.00472       0.01279   
181           0.00003   0.00202 

In [90]:
#predictions
model.predict(X_test)

array([0.51131872, 0.56427903, 0.485944  , 0.54162994, 0.60998913,
       0.49774826, 0.45816677, 0.62368119, 0.5506726 , 0.71409097,
       0.40306073, 0.65872936, 0.50326857, 0.43397239, 0.50171989,
       0.38133262, 0.43790115, 0.34783173, 0.41435186, 0.57940733,
       0.41314184, 0.64414934, 0.59572046, 0.28266521, 0.46902498,
       0.63419531, 0.49688098, 0.45285474, 0.35770391, 0.47097639])

In [91]:
#actual values
np.array(y_test)

array([0.387482, 0.58339 , 0.538688, 0.558586, 0.611137, 0.507826,
       0.459766, 0.625362, 0.602874, 0.638545, 0.393563, 0.57101 ,
       0.611679, 0.63742 , 0.487407, 0.305429, 0.400088, 0.32648 ,
       0.305062, 0.644954, 0.418622, 0.56161 , 0.577802, 0.432439,
       0.431674, 0.596362, 0.470422, 0.408598, 0.341435, 0.469928])

In [92]:
import math
math.sqrt(32)

5.656854249492381

In [95]:
mse(y_test, model.predict(X_test))

0.004922629074460124

In [96]:
math.sqrt(0.004922629074460124)

0.07016145005955994

In [ ]:
17

In [ ]:
####################################

In [98]:
0.511318720 + 0.07016145005955994 

0.58148017005956

In [97]:
0.511318720 - 0.07016145005955994 

0.4411572699404401

In [ ]:
17.5 ----  16.5